### ISSUE TITLE
Error while using SynchronousMessagingAPI service of event mesh messaging default plan

### ISSUE THREAD

**Issue by gamer-gtx-260** [SAP/cloud-sdk-java#137]
## Issue Description
Error while using SynchronousMessagingAPI service of event mesh messaging default plan for java. 

Important information:
Using this api https://api.sap.com/api/SAPEventMeshDefaultMessagingAPIs/cloud-sdk/Java to generate, after removing oneof, anyof from yaml. The api client is generated successfully.

- Expected outcome: Using SynchronousMessagingApi class and method queuesQueueNameMessagesPost to post to event mesh queue by passing a simple payload file in json format. Expected outcome is to send event with file's contents
- Actual outcome: The event is sent successfully but the payload is the file path and not the file content
- Potentially missing information (open questions you might have): any-content-type is not allowed as a media type. this had to be commented to proceed further
- Event mesh does not accept media type multipart/form-data but the input signature has java.io.File as payload. This does not work

### Impact / Priority

 
Affected development phase: Development
 
Impact:  Inconvenience

Timeline: As soon as possible

## Error Message

```
Invalid mime type "any-content-type": does not contain '/'
```

* SDK Version: 4.26.0

* Project type:
    * SDK Maven Archetype
    
* Platform:
    * Cloud Foundry

Work-around:
1. Comment any-content-type hardcoded mime type in SynchronousMessagingApi=>queuesQueueNameMessagesPost()
2. Change signature File to Object in SynchronousMessagingApi=>queuesQueueNameMessagesPost()

**Comment by CharlesDuboisSAP** [comment]
There are two ways of fixing the specification:
- The quickest option would be to edit the spec file to replace `any-content-type:` by `application/json:` or `text/plain:` on the broken variables and methods. But it seems you already found a workaround by editing the generated Java files.
- But you can also reach out to the [SAP Event Mesh team directly](https://answers.sap.com/tags/73554900100800000765) or use component id `BC-CP-EM-MES` if you have access to [service now](https://support.sap.com/en/index.html) and ask the team for a fix on the spec file.
