### ISSUE TITLE
Missed class after upgrade to Cloud SDK 5

### ISSUE THREAD

**Issue by adamandre79** [SAP/cloud-sdk-java#183]
Hello,

we want to upgrade to Cloud SDK 5 and also followed the steps described in this guide:
https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps

But after that we get the error that the following class could not be found anymore:
```
com.sap.cloud.sdk.datamodel.odata.client.request.ODataRequestResultGeneric;
```

We use this class after reading an at designtime unknown OData service.
During runtime we use the class to get the result from the OData service.

Could you please advise how to replace this class?

We had also problem with this class after upgrade to version 4 of the cloud SDK.
So what can we do to avoid such problems in the future?

Best regards
André

**Comment by CharlesDuboisSAP** [comment]
Hello André,

This class and module stayed unchanged from v4 to v5.
There might be some leftover v4 dependencies. [Please send us your dependency tree:](https://sap.github.io/cloud-sdk/docs/java/guides/manage-dependencies#updating-the-sap-cloud-sdk-version)
```sh
mvn dependency:tree
```
If you find Cloud SDK modules on version 4, [please only define v5 on the sdk-bom](https://sap.github.io/cloud-sdk/docs/java/guides/manage-dependencies#the-sap-cloud-sdk-bill-of-material) and no other module.

**Comment by adamandre79** [comment]
Hello @CharlesDuboisSAP ,

the mentioned class in included in module  `com.sap.cloud.sdk.datamodel:odata-client`.
After adding the bom this module is not included anymore.

I can also not find this modul in our artifactory, there only version 4.9.0 
![image](https://github.com/SAP/cloud-sdk-java/assets/78218751/3f8db528-412b-4abe-9f56-587dafa903b2)

Here is the dependency tree:
[dependency_tree.txt](https://github.com/SAP/cloud-sdk-java/files/13634313/dependency_tree.txt)

Regards
André

**Comment by MatKuhr** [comment]
Hi André,

the module is present on [maven central](https://central.sonatype.com/artifact/com.sap.cloud.sdk.datamodel/odata-client) and should be mirrored by the Artifactory (latest once you try to download it from there). 

And it is indeed present [here](https://int.repositories.cloud.sap/artifactory/proxy-3rd-party-repo1-maven-cache/com/sap/cloud/sdk/datamodel/odata-client/5.0.0/).

**Comment by adamandre79** [comment]
Hi @MatKuhr ,

you are right it is working now, no idea why I got an dependency error before.
But no I needed to add the dependency for the odata-client manually in our pom which was before this included somewhere.

I did it and get now no syntax errors anymore.
We need to check now if the functionality works or also other dependencies are missing.

I close the issue for now.

Regards
André
