### ISSUE TITLE
SAP Cloud SDK V5 Cannot Generated By Maven Command

### ISSUE THREAD

**Issue by ORASTARK** [SAP/cloud-sdk-java#204]
cmd> mvn archetype:generate -DarchetypeGroupId=com.sap.cloud.sdk.archetypes -DarchetypeArtifactId=spring-boot3 -DarchetypeVersion=RELEASE
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.2.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[WARNING] No archetype found in remote catalog. Defaulting to internal catalog
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
Downloading from central: https://repo.maven.apache.org/maven2/com/sap/cloud/sdk/archetypes/spring-boot3/maven-metadata.xml
[WARNING] Could not transfer metadata com.sap.cloud.sdk.archetypes:spring-boot3/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): proxy authentication failed for https://repo.maven.apache.org/maven2/com/sap/cloud/sdk/archetypes/spring-boot3/maven-metadata.xml, status: 407 Proxy Authentication Required
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.149 s
[INFO] Finished at: 2023-12-28T10:39:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.sap.cloud.sdk.archetypes:spring-boot3:RELEASE) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Johannes-Schneider** [comment]
Hi @ORASTARK,

thanks for reaching out to us.

From the logs you attached, it seems like you are behind some proxy when accessing maven central:
```
[WARNING] Could not transfer metadata com.sap.cloud.sdk.archetypes:spring-boot3/maven-metadata.xml from/to central (https://repo.maven.apache.org/maven2): proxy authentication failed for https://repo.maven.apache.org/maven2/com/sap/cloud/sdk/archetypes/spring-boot3/maven-metadata.xml, status: 407 Proxy Authentication Required
```

Could you check whether you can access https://repo.maven.apache.org/maven2/com/sap/cloud/sdk/archetypes/spring-boot3/maven-metadata.xml from your browser?

For me, it contains following content, which is correct:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.sap.cloud.sdk.archetypes</groupId>
  <artifactId>spring-boot3</artifactId>
  <versioning>
    <latest>5.1.0</latest>
    <release>5.1.0</release>
    <versions>
      <version>5.0.0</version>
      <version>5.1.0</version>
    </versions>
    <lastUpdated>20231227143654</lastUpdated>
  </versioning>
</metadata>
```

To sanity check, I also just ran the same command as you did and can indeed confirm that everything is working as expected.

Best regards,
Johannes

**Comment by Johannes-Schneider** [comment]
@ORASTARK may I assume that you were able to resolve the issue?

If so, I'd appreciate if you could close this ticket.

Best regards,
Johannes
