### ISSUE TITLE
error due to com.sap.cloud.sdk.cloudplatform.connectivity.DefaultDestination's constructor is private

### ISSUE THREAD

**Issue by i036207** [SAP/cloud-sdk-java#205]
- Your code: You can get our code from https://github.tools.sap/ngl/inbound-process-service/tree/feature-db-schema
- Expected outcome: In our application we want to call other service via CAP remote service.
- Actual outcome: During debug, we found that in method com.sap.cds.services.impl.odata.RemoteODataClient.getHttpClient, it has statement httpDestination = new DefaultDestination(destination.getProperties()).asHttp();, so the constructor in com.sap.cloud.sdk.cloudplatform.connectivity.DefaultDestination,will be call, but this private method, so an error is throw. 
[mvn_tree.txt](https://github.com/SAP/cloud-sdk-java/files/13785106/mvn_tree.txt)
![Screenshot 2023-12-28 172231](https://github.com/SAP/cloud-sdk-java/assets/26956607/6221decb-8d27-4db5-b7af-d5dd73ccb1c1)
![Screenshot 2023-12-28 172454](https://github.com/SAP/cloud-sdk-java/assets/26956607/52144168-077f-451c-b83f-a4a176c1fd66)
[pom.txt](https://github.com/SAP/cloud-sdk-java/files/13785170/pom.txt)
[pom1.txt](https://github.com/SAP/cloud-sdk-java/files/13785171/pom1.txt)

**Comment by newtork** [comment]
(Related https://github.com/SAP/cloud-sdk-java/pull/201)

**Comment by KavithaSiva** [comment]
Hi @i036207,

Thanks for reaching out to us.
We are aware of this issue and are in contact with the CAP colleagues to use another API(which is compatible with both SAP Cloud SDK v4 and v5) instead of exposing the constructor.

We will let you know as soon as the issue gets resolved.

Regards,
Kavitha

**Comment by newtork** [comment]
Dear @i036207,

[We aligned with CAP on a solution](https://github.wdf.sap.corp/cds-java/cds-services/pull/3719) that is merged already and will be shipped soon as CAP version `2.6.0`, we expect.

Until then we can leave the issue open.

Kind regards
Alexander

**Comment by MatKuhr** [comment]
The [new CAP version](https://cap.cloud.sap/docs/releases/jan24) is now available, thus closing this. Please comment/re-open if the issue somehow remains.
