### ISSUE TITLE
Question: how to use `any` filtering capability for a 3rd level navigation?

### ISSUE THREAD

**Issue by s7oev** [SAP/cloud-sdk-java#345]
Hello,

I am interested in translating this OData request:

`/PackagingCompositions?$expand=items($expand=packagingElements)&$filter=items/any(i:i/packagingElements/usageCode ne 'H')`

to a Cloud SDK request. I see in the docs there is a [FilterableCollection interface with `any` method](https://sap.github.io/cloud-sdk/java-api/v5/com/sap/cloud/sdk/datamodel/odatav4/expression/FilterableCollection.html#any(com.sap.cloud.sdk.datamodel.odatav4.expression.FilterableBoolean)), and using it seems clear enough for non-navigation properties of packaging item, e.g.:

```java
req.filter(PackagingComposition.TO_ITEMS.any(PackagingCompositionItem.LEVEL_CODE.equalTo("20")))
```

But to me it is unclear how would I go for filtering on a property of `packagingElements`:
<img width="970" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/47610738/d3dcc814-9b11-47a8-9818-1088bc59f7bc">

Note that, despite the plural name, there is one packaging element actually.

Here's an example entity:

```json
{
    "identifier": "10060916",
    "description": "Water cap 2",
    "baseQuantity": 10000.000000,
    "items": [
        {
            "packagingCompositionIdentifier": "10060916",
            "packagingElementIdentifier": "10060916",
            "packagingElementVersion": "01-01-2023",
            "levelCode": "10",
            "quantity": 10000.000000,
            "unitOfMeasures_id": "PC",
            "packagingElements": {
                "identifier": "10060916",
                "version": "01-01-2023",
                "description": "Water cap 2",
                "usageCode": null
            }
        },
        {
            "packagingCompositionIdentifier": "10060916",
            "packagingElementIdentifier": "10060916",
            "packagingElementVersion": "01-01-2023",
            "levelCode": "10",
            "quantity": 5.000000,
            "unitOfMeasures_id": "PC",
            "packagingElements": {
                "identifier": "10060916",
                "version": "01-01-2023",
                "description": "Water cap 2",
                "usageCode": null
            }
        }
    ]
}
```

**Comment by CharlesDuboisSAP** [comment]
Hello Stoyko,
I'm investigating the request, could you send the `PackagingComposition` specification?
Best regards, Charles

**Comment by s7oev** [comment]
Hey, Charles,

I am attaching the [metadata](https://github.com/SAP/cloud-sdk-java/files/14511956/metadata.xml.zip), additionally you can look at the CAP CDS definitions [here](https://github.tools.sap/smrdp/smrdp-outbound-api/blob/master/srv/cds/packComp-service.cds#L22).

Best,
Stoyko

**Comment by s7oev** [comment]
Hey, Charles,

Indeed, this seems to be a valid workaround for our use-case. Thanks for the support!

Best,
Stoyko
