### ISSUE TITLE
SOAPRequest deprecated from Cloud SDK 5.4.0 version

### ISSUE THREAD

**Issue by AmnaNizarHussain** [SAP/cloud-sdk-java#354]
Hi Team,

I have noticed that the SOAPRequest class has been deprecated after the recent Cloud SDK changes and would like to know what could be an alternative for the same.

Regards,
Amna

**Comment by AnimeshKumar03** [comment]
Hi @Johannes-Schneider ,

I understand there are still many SOAP based APIs exposed by SAP and Cloud SDK provides the convenience of consuming these APIs. 

Dont you think this has a wider impact on the solutions (_Both for SAP as well as Custom Built applications for System to System Communications_) relying on Cloud SDK to connect with SAP SOAP APIs?

It would be better if this was never removed and kept deprecated for future major version releases.

Thanks,
Animesh

**Comment by Johannes-Schneider** [comment]
Hi @AnimeshKumar03,

I think I'm the wrong person to answer those questions.
Therefore, pinging @jjtang1985 (product owner of the SAP Cloud SDK).

Best regards,
Johannes

**Comment by jjtang1985** [comment]
Hi @AnimeshKumar03 ,

Thank you very much for approaching us.

> Dont you think this has a wider impact on the solutions (Both for SAP as well as Custom Built applications for System to System Communications) relying on Cloud SDK to connect with SAP SOAP APIs?

We have no ideas about how many users are using SAP SOAP APIs.
However, from our statistics of the SDK users, the share of SOAP users is limited.

The deprecation message is an indicator that we will remove that in the future (no timeline so far), so users can find other alternatives:
- other SDKs or copy the same code
- switch to OData based API if possible

Thank you very much for your understanding.
Best regards,
Junjie
