### ISSUE TITLE
Business logging functionality in SDK 5.0

### ISSUE THREAD

**Issue by I328160** [SAP/cloud-sdk-java#377]
Hello colleague,

We wanted to use business logging functionality in our CAP Java application which is cloud SDK 5.0.
When we went through the document https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps#remove-or-replace-modified-sap-cloud-sdk-dependencies, we see that **com.sap.cloud.sdk.services:scp-business-logging-all** is deprecated.

Will there be any support for this SDK service in 5.0 ? Also is there any alternative way to use it?

**Comment by CharlesDuboisSAP** [comment]
The replacement for business logging can now be generated instead by using the [OData](https://sap.github.io/cloud-sdk/docs/java/features/odata/vdm-generator) and [OpenAPI](https://sap.github.io/cloud-sdk/docs/java/features/rest/generate-rest-client) generators with the EDMX and JSON specifications of the service. It was documented in the [release notes](https://sap.github.io/cloud-sdk/docs/java/v4/release-notes#4140---may-12-2023).

**Comment by MatKuhr** [comment]
In addition, once you generated the code, you get destinations for using the API as documented [here](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/service-bindings). I.e. that is replacing the previous `ScpBusinessLoggingDestinationLoader`.
