### ISSUE TITLE
HTTP destination 

### ISSUE THREAD

**Issue by anlauft** [SAP/cloud-sdk-java#427]
Hello SAP Cloud SDK team,

we're using a HTTP destination to a cloud system to fetch data.
This works fine on BTP. 

As we want to execute the request using the dest in BAS we're facing some trouble. 

As there is no documentation how to use CAP with the destination service running on CF we added an env variable:

export destinations="[{"name": "MY_API","url": "https://myapi.com","proxyConfiguration": {"host": "127.0.0.1","port": 8887,"protocol":"http"}}]"

As we execute it we're getting the message: 

The destination URI must be absolute OR empty.

![image](https://github.com/SAP/cloud-sdk-java/assets/168192612/d89aed4f-b564-4af7-a38c-871a79c3bb17)

```
Caused by: com.sap.cloud.sdk.cloudplatform.connectivity.exception.DestinationPathsNotMergeableException: The destination URI must be absolute OR empty.
        at com.sap.cloud.sdk.cloudplatform.connectivity.UriPathMerger.merge(UriPathMerger.java:59) ~[cloudplatform-connectivity-5.8.0.jar:na]
        at com.sap.cloud.sdk.cloudplatform.connectivity.HttpClientWrapper.wrapRequest(HttpClientWrapper.java:116) ~[connectivity-apache-httpclient4-5.8.0.jar:na]
```

**Comment by Johannes-Schneider** [comment]
Hi @anlauft,

I'm assuming that you are referring to [the SAP Business Application Studio](https://www.sap.com/products/technology-platform/business-application-studio.html) by _"BASF"_, is that correct?

If so, you have to provide your `destinations` environment variable in the form that is [documented here](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/running-locally#on-premise-connectivity-from-business-application-studio-bas).

Hope that helps.

Best regards,
Johannes

**Comment by Johannes-Schneider** [comment]
Thanks for sharing the exception.
Unfortunately, it doesn't seem to be as helpful as I hoped it would be.

Therefore, would you be able to instead share `DEBUG` logs of your local application execution?

**Comment by KavithaSiva** [comment]
I am closing this issue as there has not been an update for more than two weeks. Please feel free to re-open if that's not the case and you have the necessary logs for us to analyse further.

**Comment by KavithaSiva** [comment]
@anlauft Could you please provide the DEBUG logs asked for?
