### ISSUE TITLE
Update to Axis 1.8.X

### ISSUE THREAD

**Issue by i742750** [SAP/cloud-sdk-java#436]
Axis 1.7.9 came out 2 years ago and contain security issues,
it has incompatible change with the 1.8 version, the rest of the application are still under 1.7.9 so we must still use this version and cannot upgrade to the newer one

**Comment by KavithaSiva** [comment]
Hi @i742750,

The switch to Axis2 `1.8.2` wasn't straightforward and seemed to require additional effort from us.
As the `soap` module (Axis2 is used here) is deprecated, we decided to not spend additional effort here.

You could also consider making a contribution to us to update `Axis2` as unfortunately I don't think this would be prioritised anytime soon on our side.

Regards,
Kavitha

**Comment by newtork** [comment]
I'm sorry to close the ticket, but as long as (presumably) no-one is willing to work on it, there's no reason to keep it open.

@jjtang1985

**Comment by newtork** [comment]
(fix state)
