### ISSUE TITLE
`ODataRequestRead` with https://<tenant_url>/api/v1/dwc/catalog/spaces('<space_id>')/assets('<asset_id>') results in "Unable to read OData 4.0 response."

### ISSUE THREAD

**Issue by KarlHakanNordgren** [SAP/cloud-sdk-java#443]
The documentation [here](https://help.sap.com/docs/SAP_DATASPHERE/43509d67b8b84e66a30851e832f66911/7a453609c8694b029493e7d87e0de60a.html?locale=en-US) says that hitting 

https://<tenant_url>/api/v1/dwc/catalog/spaces('<space_id>')/assets('<asset_id>')

will result in a "description of a particular asset, including links to its metadata and data" but the following results in "Unable to read OData 4.0 response."

> ODataRequestRead(
>     "/api/v1/dwc/catalog/spaces('$spaceId')",
>.    ODataResourcePath.of("assets('$assetId')"),
>.    "",
>      ODataProtocol.V4
>     ).execute(httpClient)`

**Comment by jjtang1985** [comment]
duplicate #444

**Comment by KarlHakanNordgren** [comment]
> duplicate #444

@jjtang1985 : No they are similar but they are not the same. I'll reopen!
