### ISSUE TITLE
`ODataRequestRead` with https://<tenant_url>/api/v1/dwc/consumption/relational/<space_id>/<asset_id>/$metadata results in 406

### ISSUE THREAD

**Issue by KarlHakanNordgren** [SAP/cloud-sdk-java#444]
The documentation [here](https://help.sap.com/docs/SAP_DATASPHERE/43509d67b8b84e66a30851e832f66911/7a453609c8694b029493e7d87e0de60a.html?locale=en-US) says that hitting 

https://<tenant_url>/api/v1/dwc/consumption/relational/<space_id>/<asset_id>/$metadata

will retrieve metadata but the following results in a 406 response.

> ODataRequestRead(
>     "/api/v1/dwc/consumption/relational/('$spaceId')/('$assetId')/\$metadata"
>.    ODataResourcePath.of(""),
>.    "",
>      ODataProtocol.V4
>     ).execute(httpClient)`

**Comment by KarlHakanNordgren** [comment]
The reason is that the JSON looks like this

`{
    "@odata.context": "XX",
    "name": "XX",
    "label": "XX",
    "spaceName": "XX",
    "assetRelationalMetadataUrl": null,
    "assetRelationalDataUrl": null,
    "assetAnalyticalMetadataUrl": "XX",
    "assetAnalyticalDataUrl": "XX",
    "supportsAnalyticalQueries": true,
    "hasParameters": false
}`

But the code to parse the JSON [here](https://github.com/SAP/cloud-sdk-java/blob/2f831eef1305530351a1b1def0475a1438222b26/datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/ODataResponseDeserializer.java#L128) requires it to have a `value` node.

**Comment by newtork** [comment]
May I ask, what do you expect from calling GET to an OData entity `/$metadata` endpoint?
