### ISSUE TITLE
Is it possible to submit SQL queries via `SAP/cloud-sdk-java`? 

### ISSUE THREAD

**Issue by KarlHakanNordgren** [SAP/cloud-sdk-java#446]
Is it possible to submit SQL queries via `SAP/cloud-sdk-java`?

**Comment by KavithaSiva** [comment]
No, the SAP Cloud SDK provides abstractions for BTP services like Destination, Connectivity and helps generate typed clients for consuming OData and OpenAPI services. 
It does not provide any support for executing SQL queries.

**Comment by KarlHakanNordgren** [comment]
@KavithaSiva : Cheers!
