### ISSUE TITLE
Adding filter predicate on singleton 1:1 navigational property does not work

### ISSUE THREAD

**Issue by soumyachitnis-sap** [SAP/cloud-sdk-java#472]
Hello Colleagues,

This is with reference to a previous SDK Issue -https://github.wdf.sap.corp/MA/sdk/issues/2914

I had a similar requirement to what you replied is possible. To have an filter on a singleton 1:1 navigational property.
<img width="899" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/173021300/816b7ac7-6c05-4b4c-8d3c-bd5fcc068cdf">
 
It did work but i am not able to add an expression as in multiple filters using 'or' ,  'and'..is that limitation?

<img width="508" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/173021300/835bc517-1048-44f7-b18c-dcfb83165986">

Thank and Regards,
Soumya

**Comment by MatKuhr** [comment]
You can use the logical `and`, `or` and `not` functions on any boolean expression. Double check your parenthesis usage and compare with [this example](https://github.com/SAP/cloud-sdk-java/blob/main/datamodel/odata/odata-api-sample/src/test/java/com/sap/cloud/sdk/datamodel/odata/sample/FilterOnOneToOneNavigationPropertyTest.java#L59) 😉

**Comment by KavithaSiva** [comment]
As there have been no further updates on this issue, I am closing it for now.
