### ISSUE TITLE
Local mode - Service bindings loaded twice - Cannot get destination

### ISSUE THREAD

**Issue by cgaillydetaurines** [SAP/cloud-sdk-java#483]
Hi Colleagues,

I am trying to run my application locally but I cannot reach destination service because bindings are loaded twice from my "default-env.json" file, and DestinationServiceAdapter class does not accept having several bindings.
<br>
<img width="1136" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/153727562/94c1f771-d8d9-476b-a103-d9b595681eb7">
<br>

In the ServiceBindingMerger, the bindings are doubled:
<br>
<img width="1155" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/153727562/185ca09d-5723-410b-93c1-f0d09656bd1f">
<br>
My supposition is loaded first by SapVcapServicesServiceBindingAccessor class
<br>
<img width="1496" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/153727562/7aa07e02-1126-409b-9791-27d803267e01">
<br> And a second time by VcapServiceParser from cap.<br>
<img width="1270" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/153727562/9aae0b64-ebb5-4cb5-a14f-e61d1d2ea9b8">
Appreciate your help, Clément.

* SDK Version: 5.9.0

* Link to GitHub repo: [https://github.wdf.sap.corp/CloudConso/grdc-forms-and-reports/](GRDC)
* Project type, for example:
    * [X ] CAP Project
    * [ ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [ X] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

-----

**Comment by cgaillydetaurines** [comment]
Hi Alexander:

I have no VCAP_SERVICES env var setup on my machine.

My default-env.json: <br>
<img width="1077" alt="image" src="https://github.com/SAP/cloud-sdk-java/assets/153727562/49800e0d-d80e-4fe1-bef7-4122b855f821">
<br>
If needed, we can setup a call, I can attach easily a debugger to my env.

Tx, Clément.

**Comment by KavithaSiva** [comment]
I have sent an MR for 27th June for a screensharing session.

**Comment by newtork** [comment]
After screensharing, investigation and discussion also with CAP, we concluded:
> `cds bind` shall not be used in combination with `default-env.json`

Please approach CAP colleagues directly for a suggestion on how to start the application then.

---

Context:
* At runtime a duplicate service binding was found for "destination" service. According to _SAP Cloud SDK_, this is unexpected.
  * `DefaultServiceBindingAccessor.getInstance()` shows (among others) the following loaders, each returning the same entries:
    * `DefaultEnvFileServiceBindingLoader` yields data via `default-env.json`.
    * `SapVcapServicesServiceBindingAccessor` yields data via `System.getenv("VCAP_SERVICES")`.
      * Presumably using `cds bind` when running the application results in environment variables being populated. Thus the information is loaded twice. This leads to an error.
