### ISSUE TITLE
JAXB (javax - guava) and Apache HttpClient version 4 - Updates?

### ISSUE THREAD

**Issue by MarcelHoell** [SAP/cloud-sdk-java#526]
The odata-client is using Google Guava library in version 33.2.1-jre, which depends on the old javax.xml library, which is outdated for some long time now.

My question therefore is, are there any plans to remove this library or introduct the jakarta xml library instead of javax?

If I explicitly remove the jaxb library from our code, I will get the following exception:
`com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

Another thing is that the odata-client is also using the old httpclient library version 4 instead of 5, are there also any plans to migrate to version 5?

**Comment by CharlesDuboisSAP** [comment]
The latest version of `guava` doesn't use `javax.xml`.

Updating the `odata-client` to `httpclient` version 5 is a breaking change that will require us to release Cloud SDK v6.

Best, Charles

**Comment by MarcelHoell** [comment]
OK, sorry for the misunderstanding regarding guava and javax. You're right, thats on our side.

Regarding httpclient v5: Will that be introduced? Are there any plans to migrate to v5? Is there a roadmap existing for that topic?

Thanks!

**Comment by jjtang1985** [comment]
Hi @MarcelHoell ,

Thank you for raising up.

Here is the [documentation](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/http-client#general-usage) about how to use Apache http client v5, if you directly use our Cloud SDK http client.

However, using http client v5 with OData has to be introduced in the next major version, and we dont have timeline for that.

Best regards,
Junjie

**Comment by KavithaSiva** [comment]
Closing this issue as switching `OData` client to use `HttpClient` v5 is not planned.
