### ISSUE TITLE
Howto mTLS

### ISSUE THREAD

**Issue by itmstr01** [SAP/cloud-sdk-java#537]
I don't know how to consume a OData-Service that is protected by mTLS.

I already have an Bearer-Token. Now I have to use mTLS using the DefaultHttpDestination.Builder.
We are using the httpClient 4 !
Where can I find some documentation?
Here my fist approach:
```
private Destination buildDestinationWithMTLSAuth(String name) throws Exception {
        String token =   ... fetch bearer token form token endpoint
        LocalDateTime validUntil =  ... served by token endpoint

        String url = ...// https://xxxxxx.yyyy.apimanagement.eu20.hana.ondemand.com:443
        String keyStorePassword = ... the keystore password;
        String applicationKey = ... the api key;

        DefaultHttpDestination.Builder destinationBuilder = DefaultHttpDestination
                .builder(url)
                .authenticationType(AuthenticationType.CLIENT_CERTIFICATE_AUTHENTICATION)
                // this enables mTLS
                .securityConfiguration(SecurityConfigurationStrategy.FROM_PLATFORM)
                .keyStore(getClientKeyStore(keyStorePassword)) // exactly one client-cert in KeyStore
                .keyStorePassword(keyStorePassword) // really needed once more?
                .trustAllCertificates() // should be removed later, setting the trustStore ...
                .property(VALID_DATE_UNTIL, validUntil) // Bearer token valid until
                .header("apikey", applicationKey)
                .header("Authorization", "Bearer " + token);
        HttpDestination destination = destinationBuilder.build();
        return destination;
    }

    private KeyStore getClientKeyStore(String keyStorePassword) throws Exception {
        String pathToKeyStore = getProperty("PathToKeyStore");

        final KeyStore keyStore = KeyStore.getInstance("PKCS12");
        keyStore.load(new FileInputStream(pathToKeyStore), keyStorePassword.toCharArray());
        return keyStore;
    }

```
Sadly currently the server-certificate is expired, so I cannot test accordingly.
I just want to be assure, that the above code works as expected.

I think I somehow have to use CF_INSTANCE_CERT and CF_INSTANCE_KEY, but I would like to deal without system properties.

Please also add an example for trustStore to validate the server-certificate.
How do I put the server-cert into the trustStore (I can fetch the certificate via Browser).

### Impact / Priority
Must be solved before end of august 2024.

### Maven
```
        <!-- SAP Cloud SDK -->
        <dependency>
            <groupId>com.sap.cloud.sdk.datamodel</groupId>
            <artifactId>odata-core</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.sdk.datamodel</groupId>
            <artifactId>odata-v4-core</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.32</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <!-- generated sources-->
            <groupId>com.sap.cloud.sdk.datamodel</groupId>
            <artifactId>odata-generator</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <!-- oauth -->
            <groupId>com.sap.cloud.sdk.cloudplatform</groupId>
            <artifactId>connectivity-oauth</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.2</version>
        </dependency>
```

**Comment by MatKuhr** [comment]
Hi Oliver, please clarify which certificate you want to use as client certificate for the communication, and where this certificate is coming from.

Using `SecurityConfigurationStrategy.FROM_PLATFORM)` together with `.keyStore(..)` doesn't make sense. The former will use the [Cloud Foundry Instance Identity](https://docs.cloudfoundry.org/devguide/deploy-apps/instance-identity.html) while the latter will use the provided certificate. If you give both, the latter will be ignored completely.

Furthermore, the Cloud SDK is first and foremost designed to use destinations from the BTP destination service. In case you are not using the destination service, where do the credentials, including the certificate, come from?

Finally, the trust store should rarely require changes. If you are connecting to any SAP-managed server this should not be required. In case you do need changes, the Cloud SDK respects the default trust store that is installed on the machine your application is running on. Alternatively, you can use the API to manually set the trust store. Please refer to the official documentation for java and other online material on how to work with trust stores (and keystores, for that matter).

**Comment by itmstr01** [comment]
Hi Matthias, our OData-Client is executed from inside a WebApp deployed on a Tomcat-Instance.
The Tomcat-Instance works on-prem.
We managed to authenticate with OAuth2 yet. But our customer wants to switch to mTLS.
I searched around several hours, but I could not find an example.
The sourcecode of cloud-sdk-java does not contain a JUnit-Test that helped me.
Please provide an example! My first approach is just an helpless first shot.

The client certificate is provided by our customer. It is contained in a Java keystore.

**Comment by MatKuhr** [comment]
I'm sorry, but you'll have to better explain your setup. From your description I can't tell what you are trying to do.

**Comment by itmstr01** [comment]
I just need to have a destination that supports mTLS.

**Comment by MatKuhr** [comment]
`DefaultHttpDestination` does that. Nothing more I can say without knowing what you want to do.
