### ISSUE TITLE
Replacement for DestinationServiceTokenExchangeStrategy.LOOKUP_ONLY

### ISSUE THREAD

**Issue by ErwanAirone** [SAP/cloud-sdk-java#570]
## Issue Description

With the deprecation of DestinationServiceTokenExchangeStrategy.LOOKUP_ONLY, fetching a destination always retrieves the authencation token, this leads to destination not found error when the destination needs to be fetched with invalid credentials.

Important information:
- Your code
```
DestinationOptions options = DestinationOptions
                    .builder()
                    .augmentBuilder(
                            DestinationServiceOptionsAugmenter
                                    .augmenter()
                                    .retrievalStrategy(retrievalStrategy))
                    .build();
```
- Expected outcome
A way to retrieve the destination without the token.
- Actual outcome
Cloud sdk will also fetch the token and if unsuccessful, the destination is not found.

### Impact / Priority

 
Affected development phase:
**Production**
Customers are now seeing destination not found when the token can not be fetched successfuly by the cloud sdk.
 
Impact:
**Inconvenience**

## Project Details

* SDK Version: 5.11.0

* Link to GitHub repo: <[irpa_commonlib](https://github.wdf.sap.corp/intelligent-rpa/irpa-commonlib)>
* Project type, for example:
    * [ ] CAP Project
    * [x ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [ x] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

-----

**Comment by MatKuhr** [comment]
For only reading destination properties, without performing auth flows, please follow [this documentation](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/btp-destination-service#if-authentication-is-not-required):

```
Collection<DestinationProperties> allDestinationProperties = service.getAllDestinationProperties();
DestinationProperties individualProperties = service.getDestinationProperties("my-destination");
```

**Comment by ErwanAirone** [comment]
Alternative proposed. Thank you.
