### ISSUE TITLE
Incorrect QueryParams encoder used in ApiClient

### ISSUE THREAD

**Issue by mvigenin** [SAP/cloud-sdk-java#582]
Hi,
We have encountered an issue with the ApiClient class when using it to connect to some SAP APIs.
The problem is due to this line:
https://github.com/SAP/cloud-sdk-java/blame/9d6b93fd41ce357ef61702eeb4e086cd3bc90aa1/datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java#L704

`URLEncoder.encode((String)values.get(i), "utf8"))` is good for encoding path variables, but when used for Query parameters, it produces incorrect encoding (for example white space is encoded with + instead of %20). This is causing problems when using API endpoints like  SAP Identity Directory API where we have "filter" query parameter with specific syntax.
Example:
Using a filter by e-mail address, where the filer is "filter=emails.value eq "john.doe@company.com""
`https://<tenant>.accounts.ondemand.com/scim/Users?filter=emails.value eq "john.doe@company.com"`

The expected encoding, that works for the API endpoint is:
`https://<tenant>.accounts.ondemand.com/scim/Users?filter=emails.value%20eq%20%22john.doe%40company.com%22`

The actual result is:
`https://<tenant>.accounts.ondemand.com/scim/Users?filter=emails.value+eq+%22john.doe%40company.com%22`

Which leads to parsing error at the endpoint ({"status":400,"message":"400 : \"The provided filter is invalid.Parsing error.\""})
There is no way to influence the encoding since the URLEncoder.encode is used prior to the final call to the destination.

I would suggest replacing the above mentioned line with this encoder:
https://docs.spring.io/spring-framework/docs/3.0.x/javadoc-api/org/springframework/web/util/UriUtils.html#encodeQueryParam(java.lang.String,%20java.lang.String)
like this: `UriUtils.encodeQueryParam((String)values.get(i), "utf8"))`

Otherwise, the OpenAPI client can't be used for the mentioned scenarios.
Note that passing already encoded values like emails.value%20eq%20%22john.doe will lead to double encoding of the % symbol like
emails.value%2520eq%2520%2522john.doe which is also incorrect and leads to syntax errors

Best regards,
Marian

**Comment by mvigenin** [comment]
I have implemented a fix for this. If you add me as a contributor, I can push a branch with the correction.

**Comment by MatKuhr** [comment]
Thanks for contributing! Please fork the repo and push your changes to your fork. Then you can raise a PR to the main repo and we'll take a look 😉

**Comment by newtork** [comment]
Thanks for your contribution 🎉
