### ISSUE TITLE
OAuth2ServiceException: Error retrieving JWT token, when trying to get Destinations.

### ISSUE THREAD

**Issue by anupriyaSap** [SAP/cloud-sdk-java#587]
## Issue Description
I have upgraded to use the 5.11.0 version of cloud sdk in my code base. However, when I am trying to get the destinations with the DestinationAccessor, I am getting the excpetion

2024-09-13T05:32:07.996+0000 [APP/PROC/WEB/0] STDOUT Caused by: com.sap.cloud.security.xsuaa.client.OAuth2ServiceException: Error retrieving JWT token. Server URI https://1(sensitive url)/oauth/token. Http status code 401. Response body '{"error":"invalid_client","error_description":"Bad credentials"}'.

Important information:
- Your code -- DestinationAccessor.getDestination(destinationName);
- Expected outcome -- Destination object
- Actual outcome - Error above

The same request with the same destionations was working with cloud sdk version 4.28
But after upgrading to 5.11.0, getting the above error.

### Impact / Priority
Our Go live is in a few days. This is of high priority.
 
Affected development phase: e.g.Release
 
Impact:  Blocked

Timeline: e.g. Go-Live code freeze is due in 1week.

```
Please paste your stracktrace here within the backticks (replacing this comment)
```

 Application Logs
Cannot paste the complete stack trace due to sensitive information.

* SDK Version: <your SAP Cloud SDK version here>
5.11.0

* Project type, for example:
    * [ ] CAP Project
* Platform:
    * [ ] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)

**Comment by CharlesDuboisSAP** [comment]
Could you send your destination configuration in BTP (don't forget to censure credentials) and the `mvn dependency:tree`

**Comment by newtork** [comment]
After two weeks without feedback, we're closing the ticket.
Please create a new one, if the issue persists.
