### ISSUE TITLE
SAP BTP Cloud SDKによるResilience機能を利用したS/4HANA ODataサービス呼出時のタイムアウト設定について

### ISSUE THREAD

**Issue by kazumi-senzaki** [SAP/cloud-sdk-java#595]
SAP BTP Cloud SDKによるResilience機能を利用したS/4HANA ODataサービス呼出時のタイムアウト設定で、タイムアウト値を2分以上たとえば「5分」に設定しても、2分でタイムアウトしてしまいます。「1分」にすると1分でタイムアウトするため、設定は効いているようですが、2分以上の指定が適用されないのが仕様なのか製品不具合なのかご確認をお願いします。なお、以下のアクセスパスにおいて、SAP Cloud SDK以外のタイムアウト設定についても確認しており、「2分」が設定されている箇所が無いことは確認済みとなります。

アクセスパス：Standalone Approuter → BTP Java アプリ (SAP Cloud SDK) → SAP Cloud Connector → Load Balancer → Web Dispatcher → S/4HANA (OData)

**Comment by newtork** [comment]
You can set the maximum HTTP client timeout globally:
```java
HttpClientFactory factory = DefaultHttpClientFactory.builder().timeoutMilliseconds(10 * 60 * 1000).build();
HttpClientAccessor.setHttpClientFactory(factory);
```

<details><summary>For sake of completeness this is also possible for Apache HTTP Client 5</summary>

```java
ApacheHttpClient5Factory factory = new ApacheHttpClient5FactoryBuilder().timeout(Duration.ofMinutes(10)).build();
ApacheHttpClient5Accessor.setHttpClientFactory(factory);
```

</details>

**Comment by kazumi-senzaki** [comment]
> HTTPクライアントの最大タイムアウトは、グローバルに設定できます(例:10分)。
> 
> ```java
> HttpClientFactory factory = DefaultHttpClientFactory.builder().timeoutMilliseconds(10 * 60 * 1000).build();
> HttpClientAccessor.setHttpClientFactory(factory);
> ```
> 
> 完全を期すために、これはApache HTTP Client 5でも可能です

ご回答ありがとうございます。
再度の確認となり申し訳ありませんが教えてください。
ご案内頂いたHTTPクライアントの最大タイムアウトの設定は、SAP BTP Cloud SDKのResilience機能のタイムアウト設定と合わせて行う必要があるという認識で合っておりますでしょうか？

**Comment by KavithaSiva** [comment]
By default in the SDK, for HTTP clients, two minutes is set as the connection timeout.
You can increase this by using the code snippets provided by my colleague.

You don't need the resilience timeout configured if you are solely interested in configuring timeouts for the HttpClient.
But, if the resilience timeout is being used for more operations in addition to HttpClients, you need to configure both timeouts.

**Comment by newtork** [comment]
Since there is no follow up question, I considered this question answered and close the issue.

**Comment by kazumi-senzaki** [comment]
ご連絡遅くなり申し訳ありません。
HTTPクライアントの最大タイムアウトの設定を実装することでタイムアウトの時間を延長することができました。
ご回答ありがとうございました。
