### ISSUE TITLE
Adaptation Required for Deprecated ScpCfDestination Methods in SAP Cloud SDK Upgrade (v4.28.0 to v5.13.0)

### ISSUE THREAD

**Issue by 95nsp2017** [SAP/cloud-sdk-java#606]
## Issue Description

Hi Colleagues,

We are in the phase of upgrading the SAP cloud sdk version from `4.28.0` to `5.13.0`.

However in the process, we noticed that after upgrading the version, the dependency `com.sap.cloud.sdk.cloudplatform:scp-cf`, as shown below, is now deprecated and is to be moved to `com.sap.cloud.sdk:sdk-core`:
![image](https://github.com/user-attachments/assets/84e33cf1-7536-44a4-b4a9-e8c80adb9d38)

Hence, we did that but then the classed pertaining to the following imports was no longer supported:
•	`ScpCfDestination`
•	`ScpCfDestinationLoader`
•	`ScpCfDestinationOptionsAugmenter`
•	`ScpCfDestinationRetrievalStrategy`

Hence, as suggested in the [migration guide](https://sap.github.io/cloud-sdk/docs/java/release-notes#changes-related-to-the-sap-btp-destination-service), we imported the relevant classes and made relevant changes.

We have a class ‘S4Destination’ which is designed to retrieve the destination information required to connect to SAP S/4HANA Cloud in a multi-tenant environment. It checks for a specific property on the destinations and ensures only one valid destination is configured, and returns an HttpDestination for communication.

However, at one of the places in our code, as shown below, we were using the method `getName()` of the `ScpCfDestination` class to retrieve the destination name from an object of the type `ScpCfDestination`.
![image](https://github.com/user-attachments/assets/fd18ed03-ab21-455c-84df-b74f0e8394fa)
Please refer the entire code from [here](https://github.tools.sap/Cloud4RM/Resource-Request/blob/master/project-integration-adapter/src/main/java/com/sap/c4p/rm/projectintegrationadapter/assignmentintegration/S4Destination.java#L48).

Now, after replacing the `ScpCfDestination` with the new `Destination` implementation, we see that this method is no more available with the new implementation and its extension class which is `DestinationProperties`.
Hence, can you please help us adapt this logic with the new Destination class provided?

Important information:
- Your code : [Destination class](https://github.tools.sap/Cloud4RM/Resource-Request/blob/master/project-integration-adapter/src/main/java/com/sap/c4p/rm/projectintegrationadapter/assignmentintegration/S4Destination.java)

### Impact / Priority

 We are in the phase of upgrading our CAP version to `3.2.0` in a month and hence need to migrate to sdk version 5 as a preparatory step which is a blocker for us now.

## Project Details
The main repo of our project as well as the sub-domain Resource Request where this code for destination resides:

- For Resource Management umbrella module : https://github.tools.sap/Cloud4RM/Resource-Management
- For pom file with the version we are migrating from : https://github.tools.sap/Cloud4RM/Resource-Request/blob/master/project-integration-adapter/pom.xml#L16
- For Resource Request module : https://github.tools.sap/Cloud4RM/Resource-Request

* SDK Version: `4.28.0`

* Link to GitHub repo: https://github.tools.sap/Cloud4RM/Resource-Management
* Project type, for example:
    * [x] CAP Project
    * [ ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [x] Cloud Foundry
    * [ ] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

-----

**Comment by 95nsp2017** [comment]
Hi @newtork,

When we consumed the new API replacing the deprecated libraries, we found the following test failures arising due to the change.
![image](https://github.com/user-attachments/assets/befa81f9-0094-44e7-98f2-96f8e5759ba6)

As we tried to analyse one of the failed tests, this is the failure logs which we got:
[Error_log_for_sdk_version_upgrade.txt](https://github.com/user-attachments/files/17303162/Error_log_for_sdk_version_upgrade.txt)

For pom file with the version we are migrating from : https://github.tools.sap/Cloud4RM/Resource-Request/blob/master/project-integration-adapter/pom.xml#L16
One of the failing test from the Resource Request module : [Failing Test Class](https://github.tools.sap/Cloud4RM/Resource-Request/blob/master/project-integration-adapter/src/integration-test/java/com/sap/c4p/rm/projectintegrationadapter/enterpriseprojectreplication/controller/EntProjReplicationNegativeAuthorizationTest.java)

Can you please help us in understanding what could have been the root cause of the error and how can we fix it?

**Comment by newtork** [comment]
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: XSUAA [in thread "main"]
	at com.sap.cloud.sdk.cloudplatform.connectivity.BtpServicePropertySuppliers.<clinit>(BtpServicePropertySuppliers.java:37)
```

Indicates a dependency version conflict.

The (missing) change was [introduced](https://github.com/SAP/cloud-sdk-java/pull/413) in Cloud SDK `5.13.0`. Please make sure to use the latest versions.

Also consider investigating for dependency conflicts: If you assume already using the latest version, then some other older Cloud SDK dependency sneaks in transitively from one of your other dependencies.

**Comment by newtork** [comment]
I have to agree with [the colleagues at CAP](https://github.tools.sap/cap/issues/issues/17003). The dependency conflict for "missing field: XSUAA" is not pointing at Cloud SDK, but at the [Service Binding library](https://github.com/SAP/btp-environment-variable-access/releases/tag/0.10.5) and whatever library repackages the code.

According to [CAP migration guide](https://cap.cloud.sap/docs/releases/jun24#important-changes%E2%9D%97%EF%B8%8F-1) min Cloud SDK version requirement is `5.9.0`.

Can you please check what happens if you use SAP Cloud SDK `5.12.0` (or earlier)? Maybe the inconsistent dependencies work in this case.

**Comment by 95nsp2017** [comment]
Hi @newtork,

Thank you so much for the response.
Got it that the issue was indeed due to a CALM library.

Thanks & Regards,
Nitya
