### ISSUE TITLE
How to mockup a destination to make it available locally to the DestinationService

### ISSUE THREAD

**Issue by gsartori** [SAP/cloud-sdk-java#620]
## Issue Description

In our Spring Boot application the following code works once deployed on the BTP CF environment but fails when run on my local machine.

**What is the right way to mockup a destination to make it available to the `DestinationService`?**

```
        DestinationService service = new DestinationService()
        DestinationProperties destinationProps = service.getDestinationProperties('TEST')
```

This is how we configured the environment variable on our project (_NOTE: The below setup works when retrieving the destination with `DestinationAccessor.getDestination(destinationName)`_)

### build.gradle
```
bootRun {
    environment = [
            // SAP Destination mock-up
            destinations: '[{"type": "HTTP", "name": "TEST", "url": "http://sap.destination.uri.not.set/", "Authentication": "NoAuthentication" }]',
    ]
}
```

SAP Cloud SDK: 5.12.0

**Comment by newtork** [comment]
`DestinationService` is a utility class that interacts with the _SAP BTP Destination Service_. It loads connection data from a `destination` service binding and runs HTTP requests against that.

Mocking at this point is difficult. You could add a custom service binding for `destination` at runtime, but then you would need to mock the HTTP server interaction too, e.g. via _Wiremock_. However this may result some significant code effort. And honestly at this point you are testing SAP Cloud SDK code, instead of your application.

Hence I wonder - why not just mock `DestinationService` itself? The class is not final, so technically is should be easily possible.

**Comment by newtork** [comment]
I like to emphasize, we recommend using `DestinationAccessor` API primarily. It has the highest level of compatibility and interoperability.

For example, adding a destination at runtime may be as easy as...
```java
var destination = DefaultHttpDestination.builder("http://my-test-system")
  .authenticationType(AuthenticationType.NO_AUTHENTICATION)
  .build();

DestinationAccessor.prependDestinationLoader((name, opt) -> {
  if("my-name".equals(name)) {
    return Try.success(destination);
  }
  return Try.failure(new DestinationNotFoundException(name));
});
```

<details><summary>(code-golf)</summary>

```java
DestinationAccessor.prependDestinationLoader((name, opt) ->
  Option.of(name).filter("my-name"::equals).toTry(DestinationNotFoundException::new).map(n -> destination));
```

</details>

And it's available:
```java
DestinationAccessor.getDestination("my-name");
```

**Comment by gsartori** [comment]
Thank you @newtork, we are using the `DestinationService` because at that point in the code we just need the destination properties without opening any connection. It was my understanding that the `DestinationAccessor` opens a connection when getting the destination.

Is that correct?

**Comment by newtork** [comment]
> Is that correct?

I see, maybe there is a misunderstanding.
* `DestinationService` will load a service binding and open a connection to the _SAP BTP Destination Service_ to load destinations properties. There is a cache in place to avoid redundant HTTP requests.
* `DestinationAccessor` has multiple _destination loaders_ assigned. One is wrapping `DestinationService` for example. Another loader looks at `"destinations"` environment variable, like you mentioned before. There might be additional loaders registered to look up destinations and their properties. This depends on your project and dependency setup.

However, **neither** API will call the target system defined in the destination properties.

The only premature request related to the destination properties may be for token-service requests, to resolve access-tokens that will be used later on. But this should not affect the target system. It will not be called unexpectedly or prematurely.

**Comment by gsartori** [comment]
Thank you very much for your explanation @newtork, I much appreciate it
