### ISSUE TITLE
How can we retrieve the SAP Passport value to use in the requests sent to an on-premise SAP installation?

### ISSUE THREAD

**Issue by gsartori** [SAP/cloud-sdk-java#621]
From our Spring Boot applicaiton on the BTP, connected to an on-premise SAP installation trough a SAP Destination, we need to pass the `sap-passport` header in our requests.

**What API can we use in this scenario?**

SAP Cloud SDK: 5.12.0

**Comment by newtork** [comment]
In SAP Cloud SDK 5 we no longer pass this header by default.
Instead you have to do this in your application explicitly.

I assume it's a two step solution:
1. get sap-passport header from incoming request
2. append header to outbound request

---

For (1) you can use any available API
 * SAP Cloud SDK [`RequestHeaderAccessor`](https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/thread-context#manipulating-http-headers)
  ```java
  RequestHeaderContainer headers = RequestHeaderAccessor.getHeaderContainer();
  String value = headers.getHeaderValues("sap-passport").getFirst();
  ```
 * Use Spring Boot API, e.g. annotation based
  ```java
  @RequestHeader HttpHeaders headers;
  
  String value = headers.get("sap-passport").getFirst();
  ```

For (2) this depends on your outbound request type.
 * Manually add header on the request object itself, e.g.
  ```java
  HttpPost post = new HttpPost("/blub");
  post.addHeader("sap-passport", "...");
  ``` 
 * [Declare custom DestinationHeaderProvider](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/http-destinations#about-headerproviders) to enable headers being added implicitly.
 * [Customize HttpClientFactory](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/http-client) to explicitly add default headers to all subsequent requests.
