### ISSUE TITLE
Error while deleting entity with complex key

### ISSUE THREAD

**Issue by alceroni** [SAP/cloud-sdk-java#669]
### Describe the Bug

Hi everyone,

we have an entity named _NotiCause_ in our data model that has a complex key with three fields:
```
protected Map<String, Object> getKey() {
    final Map<String, Object> result = Maps.newHashMap();
    result.put("NotifNo", getNotifNo());
    result.put("ItemKey", getItemKey());
    result.put("CauseKey", getCauseKey());
    return result;
}
```

If I try to delete the entity using the generated _NotiCauseDeleteFluentHelper_ I get a _405_ error with message _Raising fault. Fault name : defaultRaiseFaultPolicy_. 

### Steps to Reproduce

1. Create entity _NotiCause_ with necessary field values
2. Create DeleteFluentHelper with:
```
var fluentHelperDelete = odataService.deleteNotiCauseSet(sapCause)
```
3. Execute:
```
fluentHelperDelete.executeRequest(odataHttpDestination)
```
4. The generated request is then: 
```
DELETE /odata/NotiCauseSet(NotifNo='123456789',CauseKey='0001',ItemKey='0001')
```
5. The resulting response is: 
```
405 Method Not Allowed: {"fault":{"faultstring":"Raising fault. Fault name : defaultRaiseFaultPolicy","detail":{"errorcode":"steps.raisefault.RaiseFault"}}}
```

### Expected Behavior

If I exchange _Maps.newHashMap()_ with _Maps.newLinkedHashMap()_ in the entity's _getKey()_ method then the generated request is:
```
DELETE /odata/NotiCauseSet(NotifNo='123456789',ItemKey='0001',CauseKey='0001')
```
And the response is as expected:
```
204 No Content
```

### Used Versions

- Java and Maven version via `mvn --version`: 
```
Apache Maven 3.9.9
Java version: 21.0.5, vendor: Eclipse Adoptium
Default locale: de_DE, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```
- SAP Cloud SDK version: 5.14.0
- Spring Boot version: Spring Boot 3.3.2

### Code Examples

```java
// Your code here
```

### Log File

<details><summary>Log file</summary>
...
</details>

### Affected Development Phase

Development

### Impact

Inconvenience

**Comment by MatKuhr** [comment]
Hi @alceroni, thanks for reaching out! 

In general, [OData entity keys are key-value pairs](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) and thus are not ordered. I.e. any order should work. Please reach out to the maintainers of this particular OData V2 service to adjust the service behavior. That is, assuming the different ordering of keys really is the cause of this issue.

Until this is fixed, you can also influence the order by changing the order within the EDMX file itself.

**Comment by alceroni** [comment]
@MatKuhr the order in the EDMX file is correct. The HashMap though, being not ordered, will mess it up, though. That's why using LinkedHashMap fixes it.

**Comment by MatKuhr** [comment]
Got it. In that case extending the class and overriding the protected method is probably the workaround for now, and it sounds like you already applied that.

We can probably update the generator to use a linked hash map by default, just so that the order isn't unnecessarily (pseudo) random, at least in this particular place. Internally, we are using Olingo to parse the EDMX, so we have probably can't  guarantee the order will always be maintained. So it's probably still better not to rely on the ordering on server side. Anyhow, I'll check if we can improve the generator 😉

**Comment by alceroni** [comment]
Our workaround currently is to post-process the generated code and replace all usages of _Maps.newHashMap()_ with _Maps.newLinkedHashMap()_. It works, but we would prefer to use the generated code as is.

We have no idea where the ordering is enforced. We are still in the learning phase regarding OData, both on the Application side and the SAP side. We also use the SAP API Manager, so it is possible that the enforcing happens there. If there was a way to configure it, we would be happy to know it.

**Comment by MatKuhr** [comment]
Not sure what you mean by "SAP API Manager". Can you provide a link to the product page and explain a bit how you are using that product?

**Comment by alceroni** [comment]
I meant the API Business Hub Enterprise, which is part of the SAP Integration Suite (https://www.sap.com/products/technology-platform/integration-suite.html). I am just a Java developer implementing the Application code, so I don't have that many details how the integration suite is configured, but basically for me it is just a gateway to the actual OData Server that manages permissions and quota.

**Comment by MatKuhr** [comment]
We just released version 5.15.0 in which this is now a linked hash map, so you can remove the workaround 😉

**Comment by alceroni** [comment]
That was quick! Thanks a lot @MatKuhr , I will test it when I am back from vacation. 

Merry Christmas to you and your team

**Comment by alceroni** [comment]
Hi @MatKuhr, I just tested it and it works now off-the-shelf. Thanks a lot
