### ISSUE TITLE
Question: how to get http header info from a WrappedDestination

### ISSUE THREAD

**Issue by ktesnim** [SAP/cloud-sdk-java#84]
Hi ,

I get destination by calling  

`Try<Destination> destinationTry = tryGetDestination(destinationName);
        if (destinationTry.isSuccess()) {
            try {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("Successfully retrieved destination {}", sanitize(destinationName));
                }
                return destinationTry.get();`

 which return as  result a  **com.sap.cloud.sdk.cloudplatform.connectivity.WrappedDestination**.
My question is there any option to get **httpHeaders** info from the returned object?

* SDK Version: 4.22.0

* Link to GitHub repo: https://github.tools.sap/CALMRun/x-rn-service
* Project type, for example:
    * [x] CAP Project
    * [ ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [ ] Cloud Foundry
    * [x] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

Any help from your side will be appreciated .

Best regards,
Tesnim

**Comment by CharlesDuboisSAP** [comment]
Hello Tesnim,

You can transform the `WrappedDestination` into an `HttpDestination`:
```java
wrappedDestiantion.asHttp().getHeaders()
```

**Comment by newtork** [comment]
Since no further response came back, I think the answer is sufficient.
Please create a new ticket, if you encounter any problem with the suggested solution.
